### ISSUE TITLE
Use std library http.headers object

### ISSUE THREAD

**Issue by daurnimator** [ducdetronquito/h11#27] opened 2020-07-11 23:20 UTC
events/headers.zig currently contains its own header type; use the one from zig's standard library `std.http.headers`.

**Comment by ducdetronquito** [comment] 2020-07-15 11:40
Hi @daurnimator,

Good idea. I proposed some changes in `std.http` in order to reuse code from the standard library: if you have time to check it out, the issue is here: https://github.com/ziglang/zig/issues/5875.

**Comment by ducdetronquito** [comment] 2020-10-03 10:14
As the headers multimap is not part of the standard library anymore, I close this issue.
My objective is to provide a headers multimap implementation within the [http](https://github.com/ducdetronquito/http) library !

**Closed by ducdetronquito** 2020-10-03 10:14 UTC
Labels: enhancement, question
